version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: ford_postgres
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ford_service

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: ford_adminer
    restart: always

    ports:
      - "8080:8080"

volumes:
  postgres_data: